### ISSUE TITLE
2016 dataset link

### ISSUE THREAD

**Issue by Hofsmo** [ALSETLab/Nordic44-Nordpool#2]
Hi,
The link for the 2016 dataset (https://doi.org/10.5281/zenodo.162921) doesn't work anymore.

**Comment by MaximeBaudette** [comment]
Yes it was intended to be so, even if I could have written the link would be available soon. 
Let's schedule to take care of everything during Week nr 2 or 3 next year, what do you think about that?

**Comment by Hofsmo** [comment]
Ok, let's do that.

**Comment by dietmarw** [comment]
Tomorrow is the third anniversary of this issue :-D :balloon:

**Comment by lvanfretti** [comment]
This issue is closed now. I have removed the link in the repository. If some rich Scandinavian wants to create the 2016-2XXX snapshots, go for it, but don't expect more effort in this repo.
